#NO SPACES, these are treated like strings untill they are parsed.
# Grid #
cellWidth=10
cellHeight=10
mapWidth=2500
mapHeight=2500

# UI #
uiSize = 150

uiGunHeight = 80
uiGunWidth = 150


# TIle Grid
tileWidth = 40
tileHeight = 40

# Player #
playerWidth=40
playerHeight=40
playerMoveSpeed=4

# Enemies #

#EnemySizes
smallEnemy = 40
mediumEnemy = 60
largeEnemy = 80


# # Zombie
zombieSpeed = 2

# # Ghoul
ghoulSpeed = 3

# Static Objects #

#Tables
tableWidth=100
tableHeight=50