#NO SPACES, these are treated like strings untill they are parsed.
# Grid #
cellWidth=10
cellHeight=10
mapWidth=2500
mapHeight=2500

# TIle Grid
tileWidth = 100
tileHeight = 100

# Player #
playerWidth=50
playerHeight=50
playerMoveSpeed=3

# Enemies #
!!! THUG !!!

thugWidth=40
thugHeight=40
thugDamage=10
thugHealth=

!!! DOG !!!