#these are treated like strings untill they are parsed.
# Grid #
cellWidth=10
cellHeight=10
mapWidth=2500
mapHeight=2500

# UI #
uiSize = 150

screenWidth = 1200
screenHeight = 800

uiGunHeight = 80
uiGunWidth = 150


# TIle Grid
tileWidth = 40
tileHeight = 40

# Player #
playerWidth=40
playerHeight=40
playerMoveSpeed=10

# Enemies #

# SPAWNRATES

ghoulIntensity = 10

#EnemySizes
smallEnemy = 40
mediumEnemy = 60
largeEnemy = 80


# # Zombie
zombieSpeed = 2
zombieHP = 150

# # Ghoul
ghoulSpeed = 3
ghoulHP = 100

# Static Objects #

#Tables
tableWidth=100
tableHeight=50

#Couches
couchHeight = 50
couchWidth = 100

#Water
waterWidth = 100
waterHeight = 100